<?= $this->headLink()->appendStylesheet('/media/css/products_cart.css') ?>
<h2>Meu carrinho</h2>

<div id="product_list">
	<?php 
	if(empty($this->products)) 
			echo 'Carrinho vazio :('; 
	else 
		echo $this->partial('partials/product_list.phtml', array('products' => $this->products,  'cart' => $this->cart)); 
	?>
</div>

<div>
	<?php echo "Total: R$" . $this->total; ?>
</div>

<?php if(!empty($this->products)) : ?>
<div id="actions">
	<a href="<?php echo $this->url(array("controller" => "cart", "action" => "cancel"),null,true)?>">
		Limpar carrinho
	</a>

	<a href="<?php echo $this->url(array("controller" => "cart", "action" => "close"),null,true)?>">
		Concluir compra
	</a>
</div>
<?php endif; ?>
